/**
 * @fileOverview Consolidated Ledger Import Service.
 *
 * Implements a complex horizontal scanning algorithm to consume data from a multi-section 
 * Excel workbook generated by legacy VBA scripts.
 * 
 * Section Offsets (Column indices):
 * A=0   (Bonus Summary)
 * P=15  (Monthly Bonus)
 * AB=27 (Behavior)
 * AV=47 (Financial Payroll)
 * BL=63 (Analytics)
 */

import { getFirebase } from '@/lib/firebase';
import { 
    collection, 
    doc, 
    writeBatch
} from 'firebase/firestore';
import type { 
    Employee, 
    Payroll, 
    AnnualBonusSummary,
    BonusLedgerEntry,
    BehaviorLedgerEntry,
    BehaviorAnalyticsEntry
} from '@/lib/types';
import { getEmployees, isValidEmployeeName } from './employee-service';
import { createTimestamp, coerceNumber } from '@/lib/service-utils';
import { COLLECTIONS } from '@/lib/constants';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

const CL_DATA_START = 2; // Data begins on Row 3

/**
 * Resolves the target BS period for a specific data row.
 * Scans multiple columns across the sections to find year/month identifiers.
 * 
 * @param row - The raw array of cell values.
 * @returns Object with year and month index, or null if resolution fails.
 */
const resolvePeriodFromRow = (row: any[]): { year: number, month: number } | null => {
    // AE(30) AF(31) are preferred numeric columns
    const yearNum = coerceNumber(row[30], 0);
    const monthNum = coerceNumber(row[31], 0);
    
    if (yearNum > 2000 && monthNum >= 1 && monthNum <= 12) {
        return { year: yearNum, month: monthNum - 1 };
    }

    // Fallback: Check period display columns Q(16), AX(49), BM(64)
    const periodStrings = [row[16], row[49], row[64]].map(v => String(v || '').trim());
    const dateRegex = /(\d{4})[-/](\d{1,2})/;

    for (const str of periodStrings) {
        const match = str.match(dateRegex);
        if (match) {
            const y = parseInt(match[1], 10);
            const m = parseInt(match[2], 10);
            if (y > 2000 && m >= 1 && m <= 12) {
                return { year: y, month: m - 1 };
            }
        }
    }
    
    return null;
};

/**
 * The high-density parser that processes the Master Ledger spreadsheet.
 * Iterates through rows, performs multi-anchor identity matching, and commits 
 * updates to 5 different collections in atomic batches.
 * 
 * @param grid - Matrix of spreadsheet data.
 * @param importedBy - Operator username.
 * @param onProgress - UI progress callback.
 * @returns Summary of created/updated records.
 */
export const importConsolidatedLedger = async (
    grid: any[][],
    importedBy: string,
    onProgress: (p: number, t: number) => void
) => {
    const { db } = getFirebase();
    const employees = await getEmployees();
    const employeeMap = new Map(employees.map(e => [e.name.toLowerCase().trim(), e]));
    
    const results = {
        bonusSummaries: 0,
        bonusLedger: 0,
        behaviorLedger: 0,
        payroll: 0,
        behaviorAnalytics: 0,
        newEmployees: 0
    };

    let batch = writeBatch(db);
    let writeCount = 0;
    const now = createTimestamp();

    const commitBatch = async () => {
        try {
            await batch.commit();
            batch = writeBatch(db);
            writeCount = 0;
        } catch (err: any) {
            errorEmitter.emit('permission-error', new FirestorePermissionError({ path: 'consolidated_ledger', operation: 'write' }));
            throw err;
        }
    };

    const ensureEmployee = (name: string) => {
        const lowerName = name.toLowerCase().trim();
        if (employeeMap.has(lowerName)) return employeeMap.get(lowerName)!;

        const empRef = doc(collection(db, COLLECTIONS.EMPLOYEES));
        const newEmp: Omit<Employee, 'id'> = {
            name: name.trim(),
            status: 'Working',
            wageBasis: 'Monthly',
            wageAmount: 0,
            mobileNumber: 'Not Provided',
            createdBy: importedBy,
            createdAt: now
        };
        batch.set(empRef, newEmp);
        const employee = { id: empRef.id, ...newEmp } as Employee;
        employeeMap.set(lowerName, employee);
        results.newEmployees++;
        writeCount++;
        return employee;
    };

    for (let r = CL_DATA_START; r < grid.length; r++) {
        const row = grid[r];
        if (!row || row.length < 5) continue;

        // Horizontal Identity Check: Check all 5 section anchors
        // A(0), S(18), AH(33), AY(50), BO(66)
        const identityAnchors = [row[0], row[18], row[33], row[50], row[66]]
            .map(v => String(v || '').trim())
            .filter(v => isValidEmployeeName(v));

        if (identityAnchors.length === 0) continue;
        
        const employeeName = identityAnchors[0];
        const emp = ensureEmployee(employeeName);
        const period = resolvePeriodFromRow(row);

        // Section 1: Annual Bonus Summary (A-M)
        if (isValidEmployeeName(String(row[0])) && String(row[1] || '').trim() !== '') {
            const bonusData: AnnualBonusSummary = {
                id: emp.id,
                employeeName: emp.name,
                basis: String(row[1] || ''),
                monthsWorked: coerceNumber(row[2]),
                eligibleMonths: coerceNumber(row[3]),
                avgAttendancePct: coerceNumber(row[4]),
                avgMonthlySalary: coerceNumber(row[5]),
                accruedYTD: coerceNumber(row[6]),
                recommendedBonus: coerceNumber(row[7]),
                thisPayout: coerceNumber(row[8]),
                balanceAfter: coerceNumber(row[9]),
                firstPeriod: String(row[10] || ''),
                lastPeriod: String(row[11] || ''),
                remarks: String(row[12] || '')
            };
            batch.set(doc(db, 'bonus_summaries', emp.id), bonusData, { merge: true });
            results.bonusSummaries++;
            writeCount++;
        }

        if (period) {
            const periodId = `${period.year}_${period.month}`;

            // Section 2: Bonus Ledger (P-Y)
            if (isValidEmployeeName(String(row[18]))) {
                const id = `${emp.id}_${periodId}`;
                const entry: BonusLedgerEntry = {
                    id,
                    runTime: String(row[15] || ''), // P
                    periodAD: String(row[16] || ''), // Q
                    periodBS: String(row[17] || ''), // R
                    bsYear: period.year,
                    bsMonth: period.month,
                    employeeId: emp.id,
                    employeeName: emp.name,
                    basis: String(row[19] || ''),
                    baseAmount: coerceNumber(row[20]),
                    attendancePct: coerceNumber(row[21]),
                    isEligible: String(row[22] || '').toLowerCase().includes('yes'),
                    accrual: coerceNumber(row[23]),
                    note: String(row[24] || '')
                };
                batch.set(doc(db, 'bonus_ledger', id), entry, { merge: true });
                results.bonusLedger++;
                writeCount++;
            }

            // Section 3: Behavior Ledger (AB-AS)
            if (isValidEmployeeName(String(row[33]))) {
                const id = `${emp.id}_${periodId}`;
                const entry: BehaviorLedgerEntry = {
                    id,
                    runTime: String(row[27] || ''), // AB
                    periodBS: String(row[28] || ''), // AC
                    periodAD: String(row[29] || ''), // AD
                    bsYear: period.year,
                    bsMonth: period.month,
                    bsMonthName: String(row[32] || ''), // AG
                    employeeId: emp.id,
                    employeeName: emp.name,
                    workdays: coerceNumber(row[34]),
                    onTimeDays: coerceNumber(row[35]),
                    onTimePct: coerceNumber(row[36]),
                    lateDays: coerceNumber(row[37]),
                    earlyDays: coerceNumber(row[38]),
                    missingPunches: coerceNumber(row[39]),
                    absentDays: coerceNumber(row[40]),
                    satWorked: coerceNumber(row[41]),
                    phWorked: coerceNumber(row[42]),
                    extraOkHours: coerceNumber(row[43]),
                    otHours: coerceNumber(row[44])
                };
                batch.set(doc(db, 'behavior_ledger', id), entry, { merge: true });
                results.behaviorLedger++;
                writeCount++;
            }

            // Section 4: Payroll Ledger (AV-BJ)
            if (isValidEmployeeName(String(row[50]))) { // AY
                const payrollId = `${period.year}-${period.month}-${emp.id}`;
                const entry: Omit<Payroll, 'id'> = {
                    bsYear: period.year,
                    bsMonth: period.month,
                    runTime: String(row[47] || ''), // AV
                    periodAD: String(row[48] || ''), // AW
                    periodBS: String(row[49] || ''), // AX
                    employeeId: emp.id,
                    employeeName: emp.name,
                    base: String(row[51] || ''), // AZ
                    presentDays: coerceNumber(row[52]), // BA
                    extraDays: coerceNumber(row[53]), // BB
                    leaveDays: coerceNumber(row[54]), // BC
                    regularPay: coerceNumber(row[55]), // BD
                    otPay: coerceNumber(row[56]), // BE
                    allowance: coerceNumber(row[57]), // BF
                    totalPay: coerceNumber(row[58]), // BG
                    tds: coerceNumber(row[59]), // BH
                    advance: coerceNumber(row[60]), // BI
                    netPayment: coerceNumber(row[61]), // BJ
                    regularHours: coerceNumber(row[34]) * 8, // Calc from workdays
                    otHours: coerceNumber(row[44]),
                    createdBy: importedBy,
                    createdAt: now
                };
                batch.set(doc(collection(db, COLLECTIONS.PAYROLL), payrollId), entry, { merge: true });
                results.payroll++;
                writeCount++;
            }

            // Section 5: Behavior Analytics (BL-BW)
            if (isValidEmployeeName(String(row[66]))) { // BO
                const id = `${emp.id}_${periodId}`;
                const entry: BehaviorAnalyticsEntry = {
                    id,
                    runTime: String(row[63] || ''), // BL
                    periodBS: String(row[64] || ''), // BM
                    periodAD: String(row[65] || ''), // BN
                    bsYear: period.year,
                    bsMonth: period.month,
                    employeeId: emp.id,
                    employeeName: emp.name,
                    behaviorInsight: String(row[67] || ''), // BP
                    punctualityTrend: String(row[68] || ''), // BQ
                    absencePattern: String(row[69] || ''), // BR
                    otImpact: String(row[70] || ''), // BS
                    shiftEndBehavior: String(row[71] || ''), // BT
                    performanceInsight: String(row[72] || ''), // BU
                    bestDayOfWeek: String(row[73] || ''), // BV
                    worstDayOfWeek: String(row[74] || '') // BW
                };
                batch.set(doc(db, 'behavior_analytics', id), entry, { merge: true });
                results.behaviorAnalytics++;
                writeCount++;
            }
        }

        if (writeCount >= 450) {
            await commitBatch();
        }
        onProgress(r - CL_DATA_START + 1, grid.length - CL_DATA_START);
    }

    if (writeCount > 0) await commitBatch();
    return results;
};
