// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "projectId": "testreportgen",
  "appId": "1:671245122025:web:03c816c0680afebe7af378",
  "apiKey": "AIzaSyAsknobpAc2DPWsvQMHnxoY0u-TGVt-fXI",
  "authDomain": "testreportgen.firebaseapp.com",
  "measurementId": "",
  "storageBucket": "testreportgen.appspot.com",
  "messagingSenderId": "671245122025"
};
