#!/usr/bin/env node
/**
 * Generates the relational schema from scripts/supabase/schema-spec.json:
 *
 *   supabase/migrations/0008_relational_schema.sql   tables + data move
 *   src/lib/supabase-compat/schema.generated.ts      field <-> column map
 *
 * The spec lists, per table, each app field and its SQL type (text, numeric,
 * boolean, timestamptz, jsonb). Every table becomes
 *   id text primary key, <one typed column per field>, extra jsonb
 * where `extra` holds only what does not fit: fields not in the spec, or a
 * value of the wrong type (e.g. text in a numeric field). Nothing is ever
 * dropped, so a record reads back exactly as it was written.
 *
 * Usage: node scripts/supabase/gen-schema.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const spec = JSON.parse(readFileSync(join(root, 'scripts/supabase/schema-spec.json'), 'utf8'));
const TYPES = new Set(['text', 'numeric', 'boolean', 'timestamptz', 'jsonb']);

export const toColumn = (field) => {
    const snake = field
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
        .toLowerCase();
    return snake === 'id' || snake === 'extra' ? `${snake}_field` : snake;
};

const q = (s) => `"${s.replace(/"/g, '""')}"`;
const lit = (s) => `'${s.replace(/'/g, "''")}'`;

// Indexes for the filters the app runs most.
const INDEXES = {
    attendance: [['employee_id'], ['bs_year', 'bs_month']],
    raw_machine_logs: [['bs_year', 'bs_month']],
    payroll: [['employee_id'], ['bs_year', 'bs_month']],
    behavior_ledger: [['bs_year', 'bs_month']],
    behavior_analytics: [['bs_year', 'bs_month']],
    bonus_ledger: [['employee_id']],
    transactions: [['vehicle_id'], ['party_id'], ['account_id']],
    expenses: [['vehicle_id']],
    trips: [['vehicle_id']],
    policies: [['member_id']],
    products: [['party_id']],
    purchaseOrders: [['party_id']],
    leave_requests: [['employee_id']],
    sessions: [['user_id']],
};

const tables = Object.keys(spec).sort();
const fieldRows = [];
for (const t of tables) {
    const seen = new Map();
    for (const [field, typ] of Object.entries(spec[t])) {
        if (!TYPES.has(typ)) throw new Error(`${t}.${field}: unknown type ${typ}`);
        const col = toColumn(field);
        if (seen.has(col)) throw new Error(`${t}: ${field} and ${seen.get(col)} both map to column ${col}`);
        seen.set(col, field);
        fieldRows.push([t, field, col, typ]);
    }
}

// ------------------------------------------------------------------ SQL ---
const specJson = {};
for (const [t, field, col, typ] of fieldRows) (specJson[t] ||= {})[field] = [col, typ];
for (const t of tables) specJson[t] ||= {};

const sql = `-- GENERATED by scripts/supabase/gen-schema.mjs from schema-spec.json - do not edit.
--
-- Relational schema: every table gets real typed columns instead of one
-- JSON "data" column. Field names map to snake_case columns (createdAt ->
-- created_at). Anything that does not fit a column - an unknown field or a
-- value of another type - is kept in "extra", so no value is lost.
--
-- Each table's data is copied and then checked: every record rebuilt from
-- the new columns must equal the original JSON (apart from explicit nulls,
-- which read back as absent). Any difference aborts the whole migration.

create table if not exists app.fields (
  tbl text not null, field text not null, col text not null, typ text not null,
  primary key (tbl, field)
);
truncate app.fields;
insert into app.fields (tbl, field, col, typ)
select t.key, f.key, f.value ->> 0, f.value ->> 1
from jsonb_each(${lit(JSON.stringify(specJson))}::jsonb) t, jsonb_each(t.value) f;
grant select on app.fields to anon, authenticated;

-- Timestamps are written by the app as 2025-01-02T03:04:05.678Z; read them back the same way.
create or replace function app.ts_text(t timestamptz) returns text
language sql immutable set search_path = '' as $$
  select to_char(t at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
$$;

-- Does a JSON value fit a column of this type?
create or replace function app.fits(typ text, v jsonb) returns boolean
language sql immutable set search_path = '' as $$
  select case typ
    when 'text' then jsonb_typeof(v) = 'string'
    when 'numeric' then jsonb_typeof(v) = 'number'
    when 'boolean' then jsonb_typeof(v) = 'boolean'
    when 'timestamptz' then jsonb_typeof(v) = 'string'
      and (v #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$'
    when 'jsonb' then v is not null and jsonb_typeof(v) <> 'null'
    else false
  end
$$;

-- The part of a record that does not fit its table's columns.
create or replace function app.extra_of(p_tbl text, d jsonb) returns jsonb
language sql stable set search_path = '' as $$
  select nullif(coalesce(jsonb_object_agg(e.key, e.value), '{}'::jsonb), '{}'::jsonb)
  from jsonb_each(d) e
  left join app.fields f on f.tbl = p_tbl and f.field = e.key
  where jsonb_typeof(e.value) <> 'null' and (f.field is null or not app.fits(f.typ, e.value))
$$;

-- A row (as to_jsonb(row)) back to the app's record shape.
create or replace function app.row_doc(p_tbl text, r jsonb) returns jsonb
language sql stable set search_path = '' as $$
  select coalesce((
      select jsonb_object_agg(f.field, case when f.typ = 'timestamptz'
                                            then to_jsonb(app.ts_text((r ->> f.col)::timestamptz))
                                            else r -> f.col end)
      from app.fields f
      where f.tbl = p_tbl and r ? f.col and jsonb_typeof(r -> f.col) <> 'null'
    ), '{}'::jsonb)
    || coalesce(case when jsonb_typeof(r -> 'extra') = 'object' then r -> 'extra' end, '{}'::jsonb)
$$;

-- A record without its top-level null fields (they read back as absent).
create or replace function app.without_nulls(d jsonb) returns jsonb
language sql immutable set search_path = '' as $$
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb) from jsonb_each(d) where jsonb_typeof(value) <> 'null'
$$;

-- Converts one table from (id, data jsonb) to typed columns, verifying every row.
create or replace function app.to_relational(p_tbl text) returns void
language plpgsql set search_path = '' as $$
declare
  old text := p_tbl || '__doc';
  col_defs text;
  col_list text;
  col_vals text;
  bad integer;
begin
  select coalesce(string_agg(', ' || quote_ident(col) || ' ' || typ, '' order by col), ''),
         coalesce(string_agg(', ' || quote_ident(col), '' order by col), ''),
         coalesce(string_agg(', case when app.fits(' || quote_literal(typ) || ', d.data -> ' || quote_literal(field) || ') then '
                    || case typ when 'jsonb' then 'd.data -> ' || quote_literal(field)
                                when 'text' then 'd.data ->> ' || quote_literal(field)
                                else '(d.data ->> ' || quote_literal(field) || ')::' || typ end
                    || ' end', '' order by col), '')
    into col_defs, col_list, col_vals
  from app.fields where tbl = p_tbl;

  execute 'alter table public.' || quote_ident(p_tbl) || ' rename to ' || quote_ident(old);
  execute 'alter table public.' || quote_ident(old) || ' rename constraint ' || quote_ident(p_tbl || '_pkey') || ' to ' || quote_ident(old || '_pkey');
  execute 'create table public.' || quote_ident(p_tbl) || ' (id text primary key' || col_defs || ', extra jsonb)';
  execute 'insert into public.' || quote_ident(p_tbl) || ' (id' || col_list || ', extra) select d.id' || col_vals
       || ', app.extra_of(' || quote_literal(p_tbl) || ', d.data) from public.' || quote_ident(old) || ' d';
  execute 'select count(*) from public.' || quote_ident(old) || ' d full join public.' || quote_ident(p_tbl) || ' n on n.id = d.id'
       || ' where n.id is null or d.id is null'
       || ' or app.without_nulls(d.data) is distinct from app.row_doc(' || quote_literal(p_tbl) || ', to_jsonb(n))' into bad;
  if bad > 0 then
    raise exception using message = p_tbl || ': ' || bad || ' record(s) did not survive the move unchanged';
  end if;
  execute 'drop table public.' || quote_ident(old);
  execute 'alter table public.' || quote_ident(p_tbl) || ' enable row level security';
end $$;
revoke execute on function app.to_relational(text) from public, anon, authenticated;

${tables.map(t => `select app.to_relational(${lit(t)});`).join('\n')}

${Object.entries(INDEXES).map(([t, ixs]) => ixs.map(ix => `create index on public.${q(t)} (${ix.map(q).join(', ')});`).join('\n')).join('\n')}

-- Live updates for every table (the new tables replaced the published ones).
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' loop
    if not exists (select 1 from pg_publication_tables
                   where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = r.tablename) then
      execute format('alter publication supabase_realtime add table public.%I', r.tablename);
    end if;
  end loop;
end $$;
`;

writeFileSync(join(root, 'supabase/migrations/0008_relational_schema.sql'), sql);

// One script to paste into Supabase -> SQL Editor: 0008 + 0009 in a single
// transaction, so any failed check leaves the database exactly as it was.
const rules = readFileSync(join(root, 'supabase/migrations/0009_relational_rules.sql'), 'utf8');
writeFileSync(join(root, 'supabase/relational_upgrade.sql'),
    `-- Run once in Supabase -> SQL Editor. Converts every table to typed columns\n` +
    `-- (0008) and re-applies the access rules for them (0009), all in one\n` +
    `-- transaction: if any record would change, nothing is applied.\nbegin;\n\n${sql}\n${rules}\ncommit;\n`);

// ------------------------------------------------------------------- TS ---
const ts = [];
ts.push(`// GENERATED by scripts/supabase/gen-schema.mjs from schema-spec.json - do not edit.
/* eslint-disable */
export type ColumnType = 'text' | 'numeric' | 'boolean' | 'timestamptz' | 'jsonb';
/** Per table: app field -> [column, type]. Fields not listed live in \`extra\`. */
export const SCHEMA: Record<string, Record<string, readonly [string, ColumnType]>> = {`);
for (const t of tables) {
    const cols = fieldRows.filter(r => r[0] === t);
    ts.push(`    ${JSON.stringify(t)}: {${cols.map(([, f, c, ty]) => `\n        ${JSON.stringify(f)}: [${JSON.stringify(c)}, ${JSON.stringify(ty)}],`).join('')}${cols.length ? '\n    ' : ''}},`);
}
ts.push('};\n');
writeFileSync(join(root, 'src/lib/supabase-compat/schema.generated.ts'), ts.join('\n'));

console.log(`${tables.length} tables, ${fieldRows.length} columns written.`);
